src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import register

app_name = 'accounts'

urlpatterns = [
	
	path('register/', register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='accounts:login'), name='logout'),
	
]

src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from post.views import (

    index, 
    blog, 
    post, 
    search,
    contact,
    post_update, 
    post_delete, 
    post_create
)

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('blog/', blog, name='blog'),
    path('search/', search, name='search'),
    path('create/', post_create, name='post-create'),
    path('post/<id>/', post, name='post'),
    path('post/<id>/update/', post_update, name='post-update'),
    path('post/<id>/delete/', post_delete, name='post-delete'),
    path('tinymce/', include('tinymce.urls')),
    path('contact/', contact, name='contact'),
    path('accounts/', include('accounts.urls')),
    path('social/', include('allauth.urls')),
    path('members/', include('django.contrib.auth.urls')),
    # path('members/', include('members.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models

# Create your models here.

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

# FORMULAIRE DE CONNECTION
class LoginForm(AuthenticationForm):
	username = forms.CharField(label="Nom d'utilisateur", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':"Nom d'utilisateur"}))
	password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':"Mot de passe"}))


# FORMULAIRE D'INSCRIPTION
class RegisterUserForm(UserCreationForm):
	username  = forms.CharField(label="Nom d'utilisateur", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':"Nom d'utilisateur"}))
	email     = forms.CharField(label="Email", widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':"Adresse Email"}))
	password1 = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':"Mot de passe"}))
	password2 = forms.CharField(label="Confirmer mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':"Confirmer votre mot de passe"}))

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm
from post.models import Author
from django.contrib import messages
# Create your views here.

def register(request):

	if request.user.is_authenticated:
		return redirect('home')

	if request.method == 'POST':
		form = RegisterUserForm(request.POST)

		if form.is_valid():
			form.save()

			messages.success(request, 'Compte crée avec succès')
			return redirect('accounts:login')


	else:
		form = RegisterUserForm() 

	context = {'form':form}
	return render(request, 'accounts/register.html', context)

src/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Se connecter
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
  <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4 text-center">Se connecter</h4>


       <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}

          <div class="form-group">
            <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
         </div>
         
  			 {{ form.username }}

      </div> <!-- input-group.// -->
          </div> <!-- form-group// -->

          <div class="form-group">
            <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
         </div>

         {{ form.password }}
      </div> <!-- input-group.// -->
          </div> <!-- form-group// -->

          <div class="form-group">
            <a href="" class="float-right">Mot de passe oublié?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Se connecter  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Pas de compte? <a href="{% url 'accounts:register' %}">S'inscrire</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->





  
{% endblock content %}

src/templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}
	S'inscrire
{% endblock title %}

{% block content %}
	



<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
		<header class="mb-4"><h4 class="card-title text-center">S'inscrire</h4></header>

		<!-- GESTION DES ERREURS LORS DE L'INSCRIPTION -->
<!-- 
		{% if form.errors %}
			
		
		    {% if err.username %}
		    <div id="message" class="container">
		    <div  class="alert alert-danger text-center" role="alert">
		      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		        <p>Un utilisateur avec ce nom existe déjà.</p>	
		    </div>
		    </div>
		    {% endif %}


		    {% if form.password1 %}
			    <div id="message" class="container">
			    <div  class="alert alert-danger text-center" role="alert">
			      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
			        <p>Mot de passe non robuste (plus de 8 caractères)</p>	
			    </div>
			    </div>
		    {% endif %}

		{% endif %}
 -->

		<!-- FIN DE LA GESTION DES ERREURS -->

		<form action="{% url 'accounts:register' %}" method="POST">
			{% csrf_token %}


	
          <div class="form-group">
            <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
         </div>
         
  			 {{ form.username }}

          </div> <!-- input-group.// -->
          </div> <!-- form-group// -->

				<div class="form-row">
            <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
            	{{ form.email }}
				</div> <!-- form-group end.// -->


				<div class="form-row">
					<div class="form-group col-md-6">
						<span class="input-group-text"> <i class="fa fa-lock"></i> </span>
						{{ form.password1 }}
					</div> <!-- form-group end.// --> 
					<div class="form-group col-md-6">
						<span class="input-group-text"> <i class="fa fa-lock"></i> </span>
						{{ form.password2 }}
					</div> <!-- form-group end.// -->  
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> S'inscrire  </button>
			    </div> <!-- form-group// -->      
			        
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Avez-vous déjà un compte? <a href="{% url 'accounts:login' %}">Se connecter</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->




</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


	

{% endblock content %}